name: Remove topic:active on Issue Close
permissions:
  contents: read
  issues: write

on:
  issues:
    types: [closed]

jobs:
  remove-topic-active:
    runs-on: ubuntu-latest
    steps:
      - name: Remove topic:active label if present
        uses: actions/github-script@v7
        with:
          script: |
            const labelObj = context.payload.issue.labels.find(l => l.name.toLowerCase() === 'topic:active');
            if (labelObj) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                name: labelObj.name
              });
              console.log('Removed topic:active label from closed issue');
            } else {
              console.log('No topic:active label to remove');
            }