# POLICY: Strict Label Enforcement for Issues and PRs
# Only one label from each of Topic, Action, Artefact is allowed.
# All labels must match exactly one in the lists below. No extras allowed.

name: Policy - Label Enforcement

on:
  issues:
    types: [opened, labeled, unlabeled, edited]
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  enforce-label-taxonomy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Enforce label taxonomy
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            ({github, context, core}) => {
              const requiredTopics = ['Topic: foo', 'Topic: bar'];
              const requiredActions = ['Action: foo', 'Action: bar'];
              const requiredArtefacts = ['Artefact: foo', 'Artefact: bar'];
              const labels = context.payload.pull_request?.labels || context.payload.issue?.labels || [];
              const hasSingleTopic = labels.filter(label => requiredTopics.includes(label.name)).length === 1;
              const hasSingleAction = labels.filter(label => requiredActions.includes(label.name)).length === 1;
              const hasSingleArtefact = labels.filter(label => requiredArtefacts.includes(label.name)).length === 1;
              if (!hasSingleTopic || !hasSingleAction || !hasSingleArtefact) {
                const issueComment = [
                  'Your labels do not comply with the required taxonomy:',
                  '- One topic label is required: ' + requiredTopics.join(', '),
                  '- One action label is required: ' + requiredActions.join(', '),
                  '- One artefact label is required: ' + requiredArtefacts.join(', ')
                ].join('\n');
                return github.issues.createComment({
                  ...context.repo,
                  issue_number: context.issue.number,
                  body: issueComment
                }).then(() => {
                  core.setFailed('Label taxonomy enforcement failed');
                });
              }
            }
