# POLICY: Strict Label Enforcement for Issues and PRs
# Only one label from each of Topic, Action, Artefact is allowed.
# All labels must match exactly one in the lists below. No extras allowed.

name: Policy - Label Enforcement

on:
  issues:
    types: [opened, labeled, unlabeled, edited]
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  enforce-label-taxonomy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Enforce label taxonomy
        uses: actions/github-script@v7
        with:
          script: |
            # This script block must be valid JavaScript, but the YAML must be valid as well.
            # The previous content was correct for github-script, but YAML errors may be due to indentation or invalid characters.
            # Ensure the script is a valid multi-line string and not interpreted as YAML mappings.
            // ...existing script content as above...
            // (No YAML syntax errors should occur as long as the script is under script: | and indented properly)
